"""
config.py — single source of truth for paths, hyperparameters, and the Colab
bootstrap shared by notebooks 01-03.

Colab gives every notebook its own VM, so Python state is never shared between
them. The notebooks are not meant to share memory: they hand off through files
on Drive. This module makes that handoff explicit and keeps the boilerplate to
one cell.

Paste this at the top of notebooks 01, 02 and 03:

    from google.colab import drive
    drive.mount('/content/drive')
    !pip install -q pytorch-crf seqeval safetensors
    !cp /content/drive/MyDrive/crypto-ner/code/*.py /content/
    import sys; sys.path.append('/content')
    from config import *; bootstrap()

Change ROOT below once and every notebook follows. Outside Colab, set the
CRYPTO_NER_ROOT environment variable instead of editing this file.
"""

import os
import sys

# --------------------------------------------------------------------------- #
# Paths — edit ROOT only
# --------------------------------------------------------------------------- #

ROOT = os.environ.get("CRYPTO_NER_ROOT", "/content/drive/MyDrive/crypto-ner")

DATA = f"{ROOT}/data"          # inputs you upload
CODE = f"{ROOT}/code"          # utils.py, config.py, notebooks
CKPT = f"{ROOT}/ckpt"          # base model checkpoints (large)
OOF = f"{ROOT}/oof"            # out-of-fold predictions (nb 02 -> nb 03)
OUT = f"{ROOT}/analysis"       # every table destined for the paper

# ---- inputs you provide ---------------------------------------------------- #
P_RAW = f"{DATA}/dataset_mentah_twitter.csv"
P_CLEAN = f"{DATA}/dataset_preprocessed.csv"
P_GOLD_BIO = f"{DATA}/gold_standard_bio_labeled.csv"
P_SILVER_BIO = f"{DATA}/silver_standard_bio.csv"
P_SILVER_RAW = f"{DATA}/silver_standard_dataset.csv"
P_LKB_UNAMB = f"{DATA}/lkb_cleaned.json"
P_LKB_AMB = f"{DATA}/lkb_case_sensitive.json"

# ---- generated by notebook 01 ---------------------------------------------- #
P_SILVER_BIO_NAIVE = f"{DATA}/silver_standard_bio_naive.csv"
P_GOLD_STRATA = f"{OUT}/gold_strata.csv"
P_IAA_INDEX = f"{OUT}/iaa_sample_index.csv"
# ---- generated by notebook 01 (revisi tier, Agustus 2026) ------------------ #
P_TIER_REMOVAL   = f"{DATA}/lkb_tier_removal.json"
P_SILVER_BIO_V2  = f"{DATA}/silver_standard_bio_v2.csv"
BASE_DENOISED_V2 = f"{CKPT}/indobertweet-crf-base-denoised-matched-v2"

# ---- checkpoints ----------------------------------------------------------- #
BASE_DENOISED = f"{CKPT}/indobertweet-crf-base-final"   # DOI 10.57967/hf/9017
BASE_NAIVE = f"{CKPT}/indobertweet-crf-base-naive"      # trained in notebook 02

# --------------------------------------------------------------------------- #
# Model and training constants — shared so every notebook agrees
# --------------------------------------------------------------------------- #

ENCODER_TWEET = "indolem/indobertweet-base-uncased"
ENCODER_INDOB = "indobenchmark/indobert-base-p1"
ENCODER_MBERT = "bert-base-multilingual-uncased"

EPOCHS_FT = 2       # fixed fine-tuning budget, identical for every system
EPOCHS_BASE = 3     # fixed silver pre-training budget
LR_BASE, BS_BASE = 5e-5, 32
LR_FT, BS_FT = 2e-5, 16

IAA_N = 150         # size of the inter-annotator overlap sample


# --------------------------------------------------------------------------- #
# Handoff contract between notebooks
# --------------------------------------------------------------------------- #

STAGES = {
    "01 → 02": [
        (P_SILVER_BIO_NAIVE, "naive silver labels, required by the -HD ablation"),
    ],
    "01 → 03": [
        (P_GOLD_STRATA, "per-sentence stratum, used in the error breakdown"),
    ],
    "02 → 03": [
        (f"{OOF}/oof_proposed.jsonl", "out-of-fold predictions, proposed system"),
        (f"{OOF}/oof_naive_silver_ft.jsonl", "out-of-fold predictions, -HD ablation"),
    ],
}


def handoff_status(verbose=True):
    """Show which cross-notebook artifacts already exist.

    Because each notebook runs in its own VM, this file listing is the only way
    to see where the pipeline stands.
    """
    ready = {}
    for stage, items in STAGES.items():
        rows = []
        for path, desc in items:
            exists = os.path.exists(path)
            rows.append((exists, os.path.basename(path), desc))
            ready[path] = exists
        if verbose:
            print(f"\n  {stage}")
            for exists, name, desc in rows:
                mark = "ok     " if exists else "MISSING"
                print(f"    [{mark}] {name:34s} {desc}")

    if verbose:
        n = len([p for p in ready if os.path.exists(p)])
        oof_files = sorted(
            f for f in os.listdir(OOF) if f.startswith("oof_")
        ) if os.path.isdir(OOF) else []
        print(f"\n  OOF files present: {len(oof_files)}")
        for f in oof_files:
            print(f"    {f}")
        if not oof_files:
            print("    (none yet — notebook 02 has not produced any results)")
    return ready


def bootstrap(check_data=True, verbose=True):
    """Create the folder layout, verify inputs, and report pipeline state."""
    for d in (DATA, CODE, CKPT, OOF, OUT):
        os.makedirs(d, exist_ok=True)
    if "/content" not in sys.path:
        sys.path.append("/content")

    if verbose:
        print(f"ROOT = {ROOT}")
        try:
            import torch
            gpu = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU only"
            print(f"device: {gpu}")
        except ImportError:
            pass

    if check_data and verbose:
        required = [
            (P_GOLD_BIO, "nb 01, 02, 03"),
            (P_SILVER_BIO, "nb 01"),
            (P_SILVER_RAW, "nb 01"),
            (P_LKB_UNAMB, "nb 01, 02, 03"),
            (P_LKB_AMB, "nb 01, 02, 03"),
            (P_RAW, "nb 01, funnel only"),
        ]
        print("\n  Inputs:")
        missing = []
        for path, use in required:
            here = os.path.exists(path)
            size = f"{os.path.getsize(path)/1e6:.1f} MB" if here else "--"
            print(f"    [{'ok     ' if here else 'MISSING'}] "
                  f"{os.path.basename(path):34s} {size:>9s}  {use}")
            if not here:
                missing.append(path)
        if missing:
            print(f"\n  Upload the missing files to {DATA}")

    if verbose:
        handoff_status()
    return True
